# Generated by Django 2.2.4 on 2019-08-25 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tmp_name', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(through='tmp_name.GiG', to='tmp_name.Gamer'),
        ),
        migrations.AddField(
            model_name='coin',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmp_name.Game'),
        ),
        migrations.AddField(
            model_name='coin',
            name='whom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tmp_name.Gamer'),
        ),
        migrations.AddField(
            model_name='botgame',
            name='gamer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmp_name.Gamer'),
        ),
    ]
