# Generated by Django 2.2.4 on 2019-09-14 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmp_name', '0002_auto_20190825_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamer',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='gamer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='gamer',
            name='password',
        ),
    ]
