# Generated by Django 2.2.5 on 2019-09-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmp_name', '0003_auto_20190914_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='radius',
            field=models.IntegerField(default=1),
        ),
    ]
